### ISSUE TITLE
Error: TypeError: tech[method] is not a function

### ISSUE THREAD

**Issue by meliksu** [silvermine/videojs-chromecast#40] opened 2019-01-19 23:43 UTC
I get the following error message while the video is playing over chromecast:

VIDEOJS: ERROR: TypeError: tech[method] is not a function
    at get (index.js:23720)
    at Player.techGet_ (index.js:36305)
    at Player.(anonymous function) [as seekable] (http://.......index.js:38496:17)
    at LiveTracker.seekableEnd (index.js:31945)
    at SeekBar.update_ (index.js:27181)
    at SeekBar.update (index.js:27210)
    at Player.bound (index.js:16694)
    at HTMLDivElement.bound (index.js:16694)
    at HTMLDivElement.data.dispatcher (index.js:16344)
    at trigger (index.js:16480)

Dependencies
Nuxt: 2.3.4
video.js: 7.4.1

Does anyone have an idea why that happens?

EDIT: I find out, that the required method "seekable" is not implemented. Seems like that's the problem. Have you planned to implement the method?

**Comment by jthomerson** [comment] 2019-01-20 18:00
Duplicate of #32. Pull requests welcome.

**Closed by jthomerson** 2019-01-20 18:00 UTC
