### ISSUE TITLE
Cast not working on videojs 7.3.0

### ISSUE THREAD

**Issue by skoften** [silvermine/videojs-chromecast#42] opened 2019-01-29 14:26 UTC
I've successfully built the module locally and added all files in the right place. The player shows the cast icon and after clicking it generates the dialog with a list of available devices. But, after selecting a device the screen is only showing a blue chromecast icon. No video and audio is casting. 

I've tested it on a iPhone X and Samsung S7. Both in Chrome browser.

Any idea?

**Comment by jthomerson** [comment] 2019-01-29 15:20
I assume this is a duplicate of #41 (and #30 and #32). Since @skoften did not report any actual errors or anything that would help us determine what's actually happening, I can't be sure, but based on that assumption, I'm closing it.

@skoften Before submitting an issue, please review open issues to see if one of them matches yours, and please provide actual details on what's failing (for example, errors from the console, or if there are none, mention that fact). If you find that your issue differs from those mentioned above, provide more details below and we can re-open this.

**Closed by jthomerson** 2019-01-29 15:20 UTC
