### ISSUE TITLE
Error: preload method not defined.

### ISSUE THREAD

**Issue by daveferrara1** [silvermine/videojs-chromecast#30] opened 2018-11-06 23:38 UTC
Using MUX we found that calls to the tech method preload were not satisfied one we begin casting.

**Comment by yokuze** [comment] 2018-11-07 20:10
@daveferrara1 Thank you for the report. We'd like to get a little more information about the issue, if we could. As part of our code review process, we try to make sure that we understand the issue as best we can so that we can verify that a PR fully addresses it. For example:

1) What version of Video.js is used?
2) What exactly is the "MUX" you refer to? Is it [this](https://github.com/videojs/mux.js/) and if so, what version and how are you using it?
3) What are the steps to reproduce the issue?

etc.

The best way to answer these questions and to clarify an issue is to provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve). Would you be able to create one for this issue? [Here's a codepen](https://codepen.io/mluedke/pen/MzKmKq) to get you started (note that it uses VideoJS 7.3.0 and videojs-chromecast 1.1.0). This also gives us a good start toward testing a fix.

Side note: I can see from [this comment on the PR you submitted](https://github.com/silvermine/videojs-chromecast/pull/31#issue-228872477) that it's likely that something is calling the `preload` function on the player, which delegates to the active `Tech`, and our `ChromecastTech` does not currently have a `preload` function so the error is thrown. However, it would still be a good idea to have an MCVE that shows this and that we can test against.

Thanks!

**Comment by daveferrara1** [comment] 2018-11-08 18:09
Had a look at your code pen. That has a console error. I noticed the chromecast button is missing but still in the dom but it has vjs-hidden class so likely its missing because its problematic in that sandboxed iframe. 

So that pen does not cast. Maybe it used to, or your just casting the browser window (that works), and not the player in the MCVE. Maybe its a paid feature?

You got it right on -- mux is looking for the preload method. 

Would have to assume they think its common. 

We are using: 
MUX:
https://mux.com/
DOCS:
https://docs.mux.com/docs/web-integration-guide
NPM: 
https://www.npmjs.com/package/videojs-mux
UNPKG:
https://unpkg.com/videojs-mux@2.4.1/dist/videojs-mux.js

**Comment by yokuze** [comment] 2018-11-08 20:48
@daveferrara1 Sorry, I should have specified: when using the Codepen, you have to cast from the "debug" view (https://s.codepen.io/mluedke/debug/MzKmKq/xJAjOqwNbEnk) because the preview in the editor view is embedded in a [sandboxed iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox), which causes the error you noted. The "debug" view is not enclosed in an iframe. I tend to do all of my testing in the "debug" view.

Please give that a try and let me know if you have any other issues creating the MCVE.

**Comment by yokuze** [comment] 2018-11-08 20:53
A note for our reference:

The `preload` function isn't in the [list of required methods to implement when implementing a Tech][1]. However, the Video.js Player class delegates some of its function calls to the underlying Tech, one of which is the call to [preload][2]. So, if `videojsPlayerInstance.preload()` is ever called while the Chromecast Tech is active, it'll throw an error.

We should prevent throwing an error, either by implementing the `preload` function in a way that makes sense for Chromecast, or by adding a no-op function. The Youtube Tech that Video.js created uses a [no-op function][3].

Of course, doing that doesn't guarantee that it fixes the issue with MUX if MUX is relying on `preload` in some critical way, but at least it gives clients the opportunity to handle what our `preload` function returns, without running into an error when calling it.

[1]: https://docs.videojs.com/tutorial-tech_.html#required-methods
[2]: https://github.com/videojs/video.js/blob/2d682a446c58f75337c7f45b150a739f712cfa04/src/js/player.js#L2995
[3]: https://github.com/videojs/videojs-youtube/blob/f2dca0ee4c96f23b73540415468c69b6c4bd22bd/src/Youtube.js#L630

**Comment by AndrewStobie** [comment] 2019-01-04 20:56
This is only semi related but I can't get the chromecast tech to work in a simple example with preload


[pen here](https://codepen.io/PGDJ/pen/jXzymd?editors=1111)

I have a full on react app that is no longer seeming to load anything from the cast_sender script I'm wondering if that is happening here.

**Comment by jthomerson** [comment] 2019-01-04 21:16
@AndrewStobie it's not clear at all why you think the problem with your CodePen is related to this issue. If it is related to this issue, please clarify your reasoning. Also, please open your console and look at the errors that it's reporting. The first thing I saw when trying to open your CodePen was that there's a 404 because you have an invalid URL to the ChromeCast plugin JS file. There may be other issues - I'm not sure - but looking at the console should get you on the right track.

**Comment by jthomerson** [comment] 2019-11-20 18:44
@yokuze did this issue get resolved? I see #41 is closed, but it seems to have been closed by #43, which only added `seekable` and not `preload`. So, I'm not sure if #41 and this issue (#30) were really completed?

**Comment by jmattiace** [comment] 2020-05-01 18:25
Hi folks! I wanted to resurface this issue here as I have run into the same problem. Essentially, if any plugin attempts to call `preload()` (such as Mux) with the chromecast tech active, the console will display errors: 

```VIDEOJS: Video.js: preload method not defined for Chromecast playback technology. TypeError: this.tech_[method] is not a function```

@daveferrara1 has created a PR https://github.com/silvermine/videojs-chromecast/pull/31 that uses @yokuze's suggestion of a noop and I have confirmed that this in fact prevents the errors from being spewed in the console. I have also confirmed that in this case, the Mux plugin _is_ handling the errors gracefully, but videojs is still logging them to the console. So there aren't any major issues there.

Wondering if we can please merge in https://github.com/silvermine/videojs-chromecast/pull/31?

**Closed** 2020-10-04 19:27 UTC

**Comment by jthomerson** [comment] 2020-10-04 19:31
Sorry this took so long. Thanks @daveferrara1! I just published v1.2.2
