### ISSUE TITLE
Silvermine plugin crashes with latest version on video.js ^8.0.4

### ISSUE THREAD

**Issue by OriaLogic** [silvermine/videojs-chromecast#154] opened 2023-02-25 12:38 UTC
Hi,

When adding the plugin to the latest version of video.js (^8.0.4), I am having this issue in the console : 
`videojs.extend is not a function`

This error happens when I initialize the plugin : 
```
require('@silvermine/videojs-chromecast')(videojs, {
    preloadWebComponents: true,
  });
```

Does it ring a bell ? 
Lucas

**Comment by yokuze** [comment] 2023-04-09 02:29
@OriaLogic @kontrollanten Please try v1.4.1, which removes usage of the deprecated `.extends` method. We can re-open this issue if the problem isn't fixed with that version.

**Closed by yokuze** 2023-04-09 02:29 UTC
